### PR TITLE
[Fix][UX]Better event duplication working and user experience

### LINKED ISSUE #402: duplication of an event sends notification before having modified the duplicate.
1/ create an event with some participants, save
2/ edit the event in the popup and duplicate it (top right button)
=> your are immediately asked if you want to send a notification to the participants.
But this notification should be sent only when you have modified and saved this new event.

### PR DESCRIPTION
**Pull request by CPatchane**
This fix #402 and improve user experience about event duplication.

Now when the user want to duplicate an event :
* If the __event was changed__, it __asks__ if the user wants to __keep editing__ or __duplicate without save changes on the current event__ (these changes will be in the duplicated event popup)
* If the __event was not changed__, the event is __simply duplicated__

__When the event is duplicated, it's not saved yet__. The user can now __cancel the duplication by clicking on "Cancel"__ or __save the duplicate by clicking on "Create"__, like a new event creation.

### CODE REVIEW

**Comment by misstick** [comment]
@gregorylegarec : is this OK mergeable?

File: client/app/views/popover_screens/duplicate.coffee [hunk 1]
```diff
@@ -0,0 +1,38 @@
+PopoverScreenView = require 'lib/popover_screen_view'
+
+module.exports = class ConfirmDuplicatePopoverScreen extends PopoverScreenView
```
Comment (gregorylegarec) [inline client/app/views/popover_screens/duplicate.coffee]: From file name/path, I feel that the class name should be `DuplicatePopoverScreen`. Am I right ?

File: client/app/views/popover_screens/main.coffee [hunk 2]
```diff
@@ -304,26 +315,40 @@ module.exports = class MainPopoverScreen extends PopoverScreenView
...
-
-
-    # Hides popover.
-    onCancelClicked: ->
-        @cancelChanges()
-        @popover.close()
+        formModelDiffers = not _.isEqual @context.formModel.attributes,
+                                    @model.attributes
+
+        @duplicateButton.show()
```
Comment (gregorylegarec) [inline client/app/views/popover_screens/main.coffee]: It seems that you can delete lines 316 and 317. :)

Comment (CPatchane) [inline client/app/views/popover_screens/main.coffee]: You're right, there is something wrong here. I have to delete lines 322 and 323 here instead because they are already triggered at 344/345. And when we use _updatePopover, there are no duplicate buttons anymore (so doesn't need them). Thanks.

File: client/app/views/popover_screens/duplicate.coffee (hunk 1 above)
Comment (CPatchane) [inline client/app/views/popover_screens/duplicate.coffee]: I thought about that but it's not literally a duplicate popover. It's a popover to confirm if the user want to continue or not to duplication and discarding old changes. I know it's long name but maybe more explicit here. What do you think?

Comment (gregorylegarec) [inline client/app/views/popover_screens/duplicate.coffee]: Ok maybe I misunderstood its real role. If you confirm your choice, it's ok for me (and I love long self-describing names).

**Comment by gregorylegarec** [comment]
Thanks @CPatchane 👍
