### PR TITLE
Fix bug about dummy event when exporting calendar

### LINKED ISSUE #317: Don't export dummy placeholder event
Each calendar contains a dummy placeholder event. We should filter it when exporting calendar.

### PR DESCRIPTION
**Pull request by CPatchane**
Fix #317.
When the calendar app is installed for the first time a dummy event with the exact date 1901-01-01 is created. When a new calendar is created, each time, a dummy event with the date 1901-01-01 RELATED TO THE LOCAL TIMEZONE is created (so 1901-01-01 more or less 12h).
There is no way to tell the difference between the dummy event and another event from the DB, so this fix doesn't export any events for end dates before the year 1901 included.

I choose to detect only the year instead of be more accurate (we could prevent only events of 1901-01-01 and 1900-12-31) to not slow down the performance when exporting a lot of events, while using momentJS to keep date formats compatibility.

### CODE REVIEW

File: server/controllers/ical.coffee [hunk 1]
```diff
@@ -27,7 +28,12 @@ createCalendar = (calendarName, callback) ->
         return callback err if err
 
         if events.length > 0
-            calendar.add event.toIcal() for event in events
+            for event in events
+                # first time app opening calendar and new calendar dummy event
+                endDateArray = moment(event.end, 'YYYYMMDD')._a
```
Comment (gregorylegarec) [inline server/controllers/ical.coffee]: What do you think of clarifying a little bit this part by doing:
```coffeescript
if moment(event.end, 'YYYYMMDD').year() > 1901
    calendar.add event.toIcal()
```
and to avoid comment __and__ clarify code:
```coffeescript
isDummyEvent = moment(event.end, 'YYYYMMDD').year() <= 1901
if not isDummyEvent
    calendar.add event.toIcal()
```
or ever define a isDummyEvent function in the Event class which could be reused later
```coffeescript
if not event.isDummy()
     calendar.add event.toIcal() # maximum clarity in my opinion
```

Comment (gregorylegarec) [inline server/controllers/ical.coffee]: Otherwise it looks fine to me. 👍

Comment (CPatchane) [inline server/controllers/ical.coffee]: You're right about more clarity but the third solution seems to be to much complex and can slow down the performance when exporting a lot of events as there is no function isDummy() in an event object. So I changed to the second one.

**Comment by gregorylegarec** [comment]
Thanks @CPatchane 👍
